<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><AssemblyName>assetball</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AssetBall.Aws/AssetBall.Aws.csproj" />
    <ProjectReference Include="../AssetBall.Client/AssetBall.Client.csproj" />
  </ItemGroup>
</Project>
